/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import model.Despesas;
import model.TpDespesa;
import model.Transacoes;

/**
 *
 * @author leparisotto
 */
public class AdicionarDespesa extends javax.swing.JDialog {

    Despesas despesa;

    /**
     * Creates new form AdicionarDespesa
     */
    public AdicionarDespesa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeDespesa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldValorDespesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDataDespesa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricaoDespesa = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonTransporteDespesa = new javax.swing.JRadioButton();
        jRadioButtonSaudeDespesa = new javax.swing.JRadioButton();
        jRadioButtonEducacaoDespesa = new javax.swing.JRadioButton();
        jRadioButtonEntreterimentoDespesa = new javax.swing.JRadioButton();
        jRadioButtonAlimentacaoDespesa = new javax.swing.JRadioButton();
        jRadioButtonResidenciaDespesas = new javax.swing.JRadioButton();
        jRadioButtonOutrasDespesas = new javax.swing.JRadioButton();
        jButtonVoltar = new javax.swing.JButton();
        jButtonIncluirDespesa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Incluir Despesa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel1.setText("Nome: ");

        jLabel2.setText("Valor:");

        jLabel3.setText("Data:");

        jLabel4.setText("Descrição: ");

        jTextAreaDescricaoDespesa.setColumns(20);
        jTextAreaDescricaoDespesa.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricaoDespesa);

        jLabel5.setText("Tipo de Despesa:");

        buttonGroup1.add(jRadioButtonTransporteDespesa);
        jRadioButtonTransporteDespesa.setText("Transporte");

        buttonGroup1.add(jRadioButtonSaudeDespesa);
        jRadioButtonSaudeDespesa.setText("Saude");

        buttonGroup1.add(jRadioButtonEducacaoDespesa);
        jRadioButtonEducacaoDespesa.setText("Educação");

        buttonGroup1.add(jRadioButtonEntreterimentoDespesa);
        jRadioButtonEntreterimentoDespesa.setText("Entreterimento");

        buttonGroup1.add(jRadioButtonAlimentacaoDespesa);
        jRadioButtonAlimentacaoDespesa.setText("Alimentação");

        buttonGroup1.add(jRadioButtonResidenciaDespesas);
        jRadioButtonResidenciaDespesas.setText("Residencia");

        buttonGroup1.add(jRadioButtonOutrasDespesas);
        jRadioButtonOutrasDespesas.setText("Outras");

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonIncluirDespesa.setText("Incluir Despesa");
        jButtonIncluirDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirDespesaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel6.setText("Ex.: dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonTransporteDespesa)
                                    .addComponent(jRadioButtonSaudeDespesa)
                                    .addComponent(jRadioButtonEducacaoDespesa))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonOutrasDespesas)
                                    .addComponent(jRadioButtonResidenciaDespesas)
                                    .addComponent(jRadioButtonAlimentacaoDespesa)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldNomeDespesa)
                                    .addComponent(jTextFieldValorDespesa)
                                    .addComponent(jTextFieldDataDespesa)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))))
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonEntreterimentoDespesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIncluirDespesa)
                        .addGap(13, 13, 13))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldValorDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDataDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonIncluirDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(167, 167, 167)
                                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButtonTransporteDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButtonAlimentacaoDespesa))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButtonSaudeDespesa)
                                            .addComponent(jRadioButtonResidenciaDespesas))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButtonEducacaoDespesa)
                                            .addComponent(jRadioButtonOutrasDespesas))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonEntreterimentoDespesa)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonIncluirDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirDespesaActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldNomeDespesa.getText();
        double valor = Double.parseDouble(jTextFieldValorDespesa.getText());
        String data = jTextFieldDataDespesa.getText();
        String descricao = jTextAreaDescricaoDespesa.getText();

        try {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate verificacaoData = LocalDate.parse(data, dtf);

        } catch (DateTimeParseException e) {
                throw new IllegalArgumentException("Formato de data inválido. Use o formato dd/MM/yyyy.");

        }

        if (name.isEmpty() || data.isEmpty() || descricao.isEmpty() || jTextFieldValorDespesa.getText().isEmpty()) {
                throw new NullPointerException("Preencha todos os campos.");

        }
        
        try {
            if (valor <= 0) {
                throw new IllegalArgumentException("O valor deve ser maior que zero.");
            }
        } catch (NumberFormatException e) {
           throw new IllegalArgumentException("Formato inválido para o campo valor.");
        } catch (IllegalArgumentException e){
           throw new IllegalArgumentException("Erro ao gravar despesa." + " Erro: " + e.getMessage());
        }

        TpDespesa tipodespesa;
        if (jRadioButtonAlimentacaoDespesa.isSelected()) {
            tipodespesa = TpDespesa.ALIMENTACAO;
        } else {
            if (jRadioButtonEducacaoDespesa.isSelected()) {
                tipodespesa = TpDespesa.EDUCACAO;
            } else {
                if (jRadioButtonEntreterimentoDespesa.isSelected()) {
                    tipodespesa = TpDespesa.ENTRETERIMENTO;
                } else {
                    if (jRadioButtonResidenciaDespesas.isSelected()) {
                        tipodespesa = TpDespesa.RESIDENCIA;
                    } else {
                        if (jRadioButtonSaudeDespesa.isSelected()) {
                            tipodespesa = TpDespesa.SAUDE;
                        } else {
                            if (jRadioButtonTransporteDespesa.isSelected()) {
                                tipodespesa = TpDespesa.TRANSPORTE;
                            } else {
                                tipodespesa = TpDespesa.OUTRAS;
                            }
                        }
                    }
                }
            }
        }
        despesa = new Despesas();
        despesa.setData(data);
        despesa.setDescricao(descricao);
        despesa.setNome(name);
        despesa.setTipoDespesa(tipodespesa);
        despesa.setValor(valor);
        
        

        //despesa = new Despesas(tipodespesa, valor, name, data, descricao);
        //Transacoes transacoes = Transacoes(despesa);
        //Movimentos movimentos = new Movimentos();
        // movimentos.incluirMovimentos(despesa);
        
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        setVisible(false);


    }//GEN-LAST:event_jButtonIncluirDespesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdicionarDespesa dialog = new AdicionarDespesa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonIncluirDespesa;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAlimentacaoDespesa;
    private javax.swing.JRadioButton jRadioButtonEducacaoDespesa;
    private javax.swing.JRadioButton jRadioButtonEntreterimentoDespesa;
    private javax.swing.JRadioButton jRadioButtonOutrasDespesas;
    private javax.swing.JRadioButton jRadioButtonResidenciaDespesas;
    private javax.swing.JRadioButton jRadioButtonSaudeDespesa;
    private javax.swing.JRadioButton jRadioButtonTransporteDespesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescricaoDespesa;
    private javax.swing.JTextField jTextFieldDataDespesa;
    private javax.swing.JTextField jTextFieldNomeDespesa;
    private javax.swing.JTextField jTextFieldValorDespesa;
    // End of variables declaration//GEN-END:variables

    private Transacoes Transacoes(Despesas despesas) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Despesas getDespesa() {
        return despesa;
    }

}
