/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Despesas;
import model.Importador;
import model.Movimentos;
import model.Receitas;

/**
 *
 * @author Lucas
 */
public class App extends javax.swing.JFrame {
    
     Movimentos movimento = new Movimentos();
     Importador imp = new Importador();

    /**
     * Creates new form App
     */
    public App() throws FileNotFoundException {
        initComponents();
        //File arquivo = new File("C:\\Users\\leparisotto\\Desktop\\L14_municipios.csv");
        File arquivo = new File("C:\\Users\\Lucas\\Desktop\\Faculdade\\ArquivoProjeto.csv");
        imp.carregarDados(arquivo);
        movimento = imp.getMovimento();
        attSaldo();
  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMostrarSaldo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonIncluirReceita = new javax.swing.JButton();
        jButtonIncluirDespesa = new javax.swing.JButton();
        jButtonListarReceitas = new javax.swing.JButton();
        jButtonListarDespesas = new javax.swing.JButton();
        jButtonListarTransações = new javax.swing.JButton();
        jButtonSaldoPeriodo = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pagina Inicial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel1.setText("Saldo atual é de:");

        jLabelMostrarSaldo.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabelMostrarSaldo.setText("saldo");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "O que você deseja:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 14))); // NOI18N

        jButtonIncluirReceita.setText("Incluir Receita");
        jButtonIncluirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirReceitaActionPerformed(evt);
            }
        });

        jButtonIncluirDespesa.setText("Incluir Despesa");
        jButtonIncluirDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirDespesaActionPerformed(evt);
            }
        });

        jButtonListarReceitas.setText("Listar Receitas");
        jButtonListarReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarReceitasActionPerformed(evt);
            }
        });

        jButtonListarDespesas.setText("Listar Despesas");
        jButtonListarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarDespesasActionPerformed(evt);
            }
        });

        jButtonListarTransações.setText("Listar Transações");
        jButtonListarTransações.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarTransaçõesActionPerformed(evt);
            }
        });

        jButtonSaldoPeriodo.setText("Consultar Saldo (Periodo)");
        jButtonSaldoPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaldoPeriodoActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIncluirReceita)
                    .addComponent(jButtonListarTransações))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonIncluirDespesa)
                        .addGap(68, 68, 68)
                        .addComponent(jButtonListarReceitas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonListarDespesas))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonSaldoPeriodo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSair)))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluirReceita)
                    .addComponent(jButtonIncluirDespesa)
                    .addComponent(jButtonListarReceitas)
                    .addComponent(jButtonListarDespesas))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarTransações)
                    .addComponent(jButtonSaldoPeriodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMostrarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 398, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMostrarSaldo))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirReceitaActionPerformed
        // TODO add your handling code here:
        

        AdicionarReceita add = new AdicionarReceita(this, true);
        add.setVisible(true);
        Receitas receita = add.getReceitas();
        if(receita != null){
            movimento.incluirMovimentos(receita);
            attSaldo();
        }
        
    }//GEN-LAST:event_jButtonIncluirReceitaActionPerformed

    private void jButtonIncluirDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirDespesaActionPerformed
        // TODO add your handling code here:
        
        
        AdicionarDespesa add = new AdicionarDespesa(this, true);
        add.setVisible(true);
        Despesas despesa = add.getDespesa();
        
         if (despesa != null){
            movimento.incluirMovimentos(despesa);
            attSaldo();
        }
        
        
    }//GEN-LAST:event_jButtonIncluirDespesaActionPerformed

    private void jButtonListarReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarReceitasActionPerformed
        // TODO add your handling code here:
        ListarReceitas listarReceitas = new ListarReceitas();
        listarReceitas.setMovimento(movimento);
        listarReceitas.setVisible(true);
    }//GEN-LAST:event_jButtonListarReceitasActionPerformed

    private void jButtonListarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarDespesasActionPerformed
        // TODO add your handling code here:
        ListarDespesas listarDespesas = new ListarDespesas();
        listarDespesas.setMovimento(movimento);
        listarDespesas.setVisible(true);
    }//GEN-LAST:event_jButtonListarDespesasActionPerformed

    private void jButtonListarTransaçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarTransaçõesActionPerformed
        // TODO add your handling code here:
        
        ListarTransacao listarTransacao = new ListarTransacao();
        listarTransacao.setMovimentos(movimento);
        listarTransacao.setVisible(true);
    }//GEN-LAST:event_jButtonListarTransaçõesActionPerformed

    private void jButtonSaldoPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaldoPeriodoActionPerformed
        // TODO add your handling code here:
        ConsultarSaldoComData cscd = new ConsultarSaldoComData();
        cscd.setMovimento(movimento);
        cscd.setVisible(true);
    }//GEN-LAST:event_jButtonSaldoPeriodoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
         try {
             imp.setMovimento(movimento);
             File arquivo = new File("C:\\Users\\Lucas\\Desktop\\Faculdade\\ArquivoProjeto.csv");
             imp.salvarTransacoes(arquivo, movimento);
         } catch (IOException ex) {
             Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         /**
          * Nome;Valor;Data;Descrição;Tipo Receita;Tipo Despesa
test;15;12/11/2022;fff;SALARIO;
test2;10;20/10/2000;ddd;;TRANSPORTE
          */
         
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
         
         setVisible(false);
         dispose();
         System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new App().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIncluirDespesa;
    private javax.swing.JButton jButtonIncluirReceita;
    private javax.swing.JButton jButtonListarDespesas;
    private javax.swing.JButton jButtonListarReceitas;
    private javax.swing.JButton jButtonListarTransações;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSaldoPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMostrarSaldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public void attSaldo(){
        String saldo = Double.toString(movimento.consultarSaldoSemPeriodo()) ;
        jLabelMostrarSaldo.setText(saldo);
    }
    
    
}
